### Look up a vendor
GET localhost:4040/vendor/get/Mark

### Create a resource sugar with a price of 6.5
GET localhost:4040/create-resource/Sugar/sugar/6.5

### Check out the new resource
GET localhost:4040/resource/4

### Get an existing warehouse
GET localhost:4040/warehouse/find/Mark/iron_ore